### ISSUE TITLE
30,000 x 20,000 px images?

### ISSUE THREAD

**Issue by mmstec** [cytomine/Dockerfiles#3]
Is Cytomine capable of working with 30,000 x 20,000 px images?

**Comment by geektortoise** [comment]
Hello, 
Yes.
More explicitely, size doesn't matter. What's matter is the image format.

You can find on our Open Access Collection some images far wider than 30.000 px
Open Access Collection : https://cytomine.com/collection
A 74440 x 46640 image : https://cytomine.com/collection/hsm0175/human-ileum-neuroendocrine-cells

**Comment by mmstec** [comment]
Obrigado!
Marcos Morais
*linktr.ee/marcosmoraisjr*
<https://l.instagram.com/?u=https%3A%2F%2Flinktr.ee%2Fmarcosmoraisjr&e=ATPYboqBwoVQHLcktc4wRaBKcLwRRTuDyRjQqpSuX0A8VAkapu1lEwChNT_jKdPAqc7b_eQicLlcPr_eUR7m4Q&s=1>

*Teaching is the highest form of understanding.Aristotle, Greek philosopher
(384 - 322 BC)*


Em sex., 30 de jul. de 2021 às 16:26, geektortoise ***@***.***>
escreveu:
